export const CHANGE_EDUCATION = 'CHANGE_EDUCATION';

export const CHANGE_WORK = 'CHANGE_WORK';

export const CHANGE_PROJECTS = 'CHANGE_PROJECTS';

export const CHANGE_ACTIVITIES = 'CHANGE_ACTIVITIES';

export const CHANGE_LOGIN = 'CHANGE_LOGIN';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';

export const POPUP_LOGIN = 'POPUP_LOGIN';

export const POPUP_REGISTER = 'POPUP_REGISTER';
